before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/cede/main.go
    binary: cede
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
    ignore:
      - goos: darwin
        goarch: 386
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      linux: Linux
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^*.sh:'
# .goreleaser.yaml
github_urls:
  api: https://srv-git-01-hh1.alinghi.tipp24.net/api/v3/
  upload: https://srv-git-01-hh1.alinghi.tipp24.net/api/uploads/
  download: https://srv-git-01-hh1.alinghi.tipp24.net/
  # set to true if you use a self-signed certificate
  skip_tls_verify: true
